name: wook
author: wook
url: https://wook87.github.io
baseurl: /
resume_site: 
description: '개발 관련 자료 모음'
github_username: wook87
github: https://github.com/wook87
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 7822001ed41e401b49e0
    clientSecret : 319e3ad920b76bfc2e6d6049d42061030744ab4d
    repo : https://github.com/wook87/wook87.github.io
    owner : wook87
    admin : wook87
